// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_high_score = "CgkI7t2-1NsUEAIQBQ"; // <GPGSID>
        public const string achievement_run1 = "CgkI7t2-1NsUEAIQAA"; // <GPGSID>
        public const string achievement_run2 = "CgkI7t2-1NsUEAIQAQ"; // <GPGSID>
        public const string achievement_run3 = "CgkI7t2-1NsUEAIQAg"; // <GPGSID>
        public const string achievement_run4 = "CgkI7t2-1NsUEAIQAw"; // <GPGSID>
        public const string achievement_run5 = "CgkI7t2-1NsUEAIQBA"; // <GPGSID>

}

